import type {
  Category,
  HeroBubble,
  HowItWorksFeature,
  ProductSummary,
} from "./types";

export const CATEGORIES: Category[] = [
  { key: "dress", label: "Kadın Giyim" },
  { key: "shirt", label: "Erkek Giyim" },
  { key: "shoe", label: "Ayakkabı" },
  { key: "bag", label: "Çanta & Aksesuar" },
  { key: "home", label: "Ev & Yaşam" },
  { key: "cosmetics", label: "Kozmetik" },
  { key: "tech", label: "Elektronik" },
  { key: "sport", label: "Spor & Outdoor" },
  { key: "baby", label: "Anne & Bebek" },
];

export const HERO_BUBBLES: HeroBubble[] = [
  { position: 1, text: "Bu yazın terletir mi?" },
  { position: 2, text: "Düğünde giyilir mi?" },
  { position: 3, text: "Hangi beden bana uyar?" },
];

export const HOW_FEATURES: HowItWorksFeature[] = [
  {
    num: "01",
    icon: "spark",
    title: "AI'ya Sor",
    description:
      "Her ürün hakkında her şeyi sor. Yorumlardan kanıt göstererek, sana özel cevap versin.",
    example: "Bu yazın terletir mi, kankacığım?",
  },
  {
    num: "02",
    icon: "ruler",
    title: "Akıllı Beden",
    description:
      "Boyunu ve kilonu söyle, sana en doğru bedeni risk yüzdesiyle önersin. İade derdi yok.",
    example: "182cm 80kg için L %92 isabetli.",
  },
  {
    num: "03",
    icon: "hanger",
    title: "Kombin Kankası",
    description:
      "Aldığın ürünün üstüne ne giyersin? Düğün, ofis ya da tatil — senaryolu kombin önersin.",
    example: "Bunu jean ile giy, smart casual olur.",
  },
];

export const PRODUCTS: ProductSummary[] = [
  {
    slug: "tudors-oversize-tisort",
    brand: "Tudors",
    name: "Unisex Oversize %100 Pamuk Basic Beyaz Tişört",
    price: "414,98",
    risk: "low",
    riskLabel: "%8",
    rating: "4.7",
    bg: "ph-bg-1",
    placeholder: "T-Shirt · M · Beyaz",
  },
  {
    slug: "mavi-denim",
    brand: "Mavi",
    name: "Slim Fit Comfort Mavi Denim Erkek Jean Pantolon",
    price: "899,00",
    risk: "low",
    riskLabel: "%6",
    rating: "4.8",
    bg: "ph-bg-9",
    placeholder: "Denim · 32W",
  },
  {
    slug: "lcw-sweat",
    brand: "LC Waikiki",
    name: "Bisiklet Yaka Düz Standart Kalıp Pamuklu Sweat",
    price: "299,99",
    risk: "mid",
    riskLabel: "%22",
    rating: "4.3",
    bg: "ph-bg-2",
    placeholder: "Sweat · Krem",
  },
  {
    slug: "adidas-stan-smith",
    brand: "Adidas",
    name: "Stan Smith Klasik Beyaz Düşük Bilek Sneaker",
    price: "2.499,00",
    risk: "low",
    riskLabel: "%4",
    rating: "4.9",
    bg: "ph-bg-5",
    placeholder: "Sneaker · 42",
  },
  {
    slug: "beymen-ceket",
    brand: "Beymen",
    name: "Premium Yün Karışımlı Lacivert Klasik Ceket",
    price: "4.250,00",
    risk: "low",
    riskLabel: "%9",
    rating: "4.6",
    bg: "ph-bg-8",
    placeholder: "Blazer · 50",
  },
  {
    slug: "zara-pantolon",
    brand: "Zara",
    name: "Soft Touch Geniş Paça Yüksek Bel Bej Pantolon",
    price: "799,00",
    risk: "mid",
    riskLabel: "%18",
    rating: "4.2",
    bg: "ph-bg-6",
    placeholder: "Pants · 38",
  },
  {
    slug: "nike-joger",
    brand: "Nike",
    name: "Tech Fleece Joger Gri Eşofman Altı",
    price: "1.899,00",
    risk: "low",
    riskLabel: "%7",
    rating: "4.8",
    bg: "ph-bg-7",
    placeholder: "Joger · L",
  },
  {
    slug: "hm-elbise",
    brand: "H&M",
    name: "Çiçek Desenli Volanlı Yazlık Midi Elbise",
    price: "549,99",
    risk: "high",
    riskLabel: "%34",
    rating: "3.9",
    bg: "ph-bg-4",
    placeholder: "Dress · 36",
  },
  {
    slug: "apple-airpods-pro",
    brand: "Apple",
    name: "AirPods Pro 2. Nesil Gürültü Engelleme Kulaklık",
    price: "8.499,00",
    risk: "low",
    riskLabel: "%3",
    rating: "4.9",
    bg: "ph-bg-11",
    placeholder: "AirPods · USB-C",
  },
  {
    slug: "penti-set",
    brand: "Penti",
    name: "Pamuklu Yüksek Bel Çamaşır Set (3'lü Paket)",
    price: "249,00",
    risk: "low",
    riskLabel: "%5",
    rating: "4.5",
    bg: "ph-bg-10",
    placeholder: "Set · M",
  },
  {
    slug: "ikea-kanepe-kilifi",
    brand: "IKEA",
    name: "Modern Linne Keten Görünümlü Kanepe Kılıfı",
    price: "1.299,00",
    risk: "mid",
    riskLabel: "%19",
    rating: "4.4",
    bg: "ph-bg-3",
    placeholder: "Cover · 3-Seat",
  },
  {
    slug: "mac-ruby-woo",
    brand: "MAC",
    name: "Ruby Woo Mat Bitişli Klasik Kırmızı Ruj",
    price: "659,00",
    risk: "low",
    riskLabel: "%4",
    rating: "4.7",
    bg: "ph-bg-12",
    placeholder: "Lipstick · 3g",
  },
];
